-- MySQL Script generated by MySQL Workbench
-- 09/15/18 15:42:07
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `EarningCall`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EarningCall` ;

CREATE TABLE IF NOT EXISTS `EarningCall` (
  `idtable1` INT NOT NULL AUTO_INCREMENT,
  `year` INT NULL,
  `Quarter` VARCHAR(100) NULL,
  `Company` VARCHAR(200) NULL,
  `Ticker` VARCHAR(50) NULL,
  `date` VARCHAR(100) NULL,
  PRIMARY KEY (`idtable1`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Presentations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Presentations` ;

CREATE TABLE IF NOT EXISTS `Presentations` (
  `idPresentations` INT NOT NULL AUTO_INCREMENT,
  `EarningCall_idtable1` INT NOT NULL,
  `Presenter` VARCHAR(200) NULL,
  `Position` VARCHAR(300) NULL,
  `Presentation` TEXT NULL,
  PRIMARY KEY (`idPresentations`),
  INDEX `fk_Presentations_EarningCall_idx` (`EarningCall_idtable1` ASC),
  CONSTRAINT `fk_Presentations_EarningCall`
    FOREIGN KEY (`EarningCall_idtable1`)
    REFERENCES `EarningCall` (`idtable1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Questions` ;

CREATE TABLE IF NOT EXISTS `Questions` (
  `idQuestions` INT NOT NULL AUTO_INCREMENT,
  `Analyst` VARCHAR(200) NULL,
  `Analyst_affiliation` VARCHAR(400) NULL,
  `Question` TEXT NULL,
  `isFollowUP` INT NULL,
  `idQuestionToWhichItFollows` INT NULL,
  `EarningCall_idtable1` INT NOT NULL,
  `hasFollowUps` INT NULL,
  PRIMARY KEY (`idQuestions`),
  INDEX `fk_Questions_EarningCall1_idx` (`EarningCall_idtable1` ASC),
  CONSTRAINT `fk_Questions_EarningCall1`
    FOREIGN KEY (`EarningCall_idtable1`)
    REFERENCES `EarningCall` (`idtable1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Answer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Answer` ;

CREATE TABLE IF NOT EXISTS `Answer` (
  `idAnswer` INT NOT NULL AUTO_INCREMENT,
  `Questions_idQuestions` INT NOT NULL,
  `Answerer` VARCHAR(500) NULL,
  `AnswerrerAffiliation` VARCHAR(500) NULL,
  `Answer` TEXT NULL,
  PRIMARY KEY (`idAnswer`),
  INDEX `fk_Answer_Questions1_idx` (`Questions_idQuestions` ASC),
  CONSTRAINT `fk_Answer_Questions1`
    FOREIGN KEY (`Questions_idQuestions`)
    REFERENCES `Questions` (`idQuestions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Features`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Features` ;

CREATE TABLE IF NOT EXISTS `Features` (
  `Answer_idAnswer` INT NOT NULL,
  `Questions_idQuestions` INT NOT NULL,
  `NumberOfTokens` INT NULL,
  `Length` INT NULL,
  `SelfReference` INT NULL,
  `SelfReferenceRatio` FLOAT NULL,
  `PassiveVoice` INT NULL,
  `PassiveVoiceRatio` FLOAT NULL,
  `AffectRatio` FLOAT NULL,
  `Similarity` FLOAT NULL,
  `Keywords` VARCHAR(500) NULL,
  `KeywordsSimilarity` FLOAT NULL,
  INDEX `fk_Features_Answer1_idx` (`Answer_idAnswer` ASC),
  INDEX `fk_Features_Questions1_idx` (`Questions_idQuestions` ASC),
  CONSTRAINT `fk_Features_Answer1`
    FOREIGN KEY (`Answer_idAnswer`)
    REFERENCES `Answer` (`idAnswer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Features_Questions1`
    FOREIGN KEY (`Questions_idQuestions`)
    REFERENCES `Questions` (`idQuestions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
